<?php

namespace CoreBundle\Repository;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(): array
    {
        return $this->findAll();
    }

    /**
     * Return the product using the slugId.
     *
     * @param string $slugId The slugId of the product that will be returned.
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     *
     * @return mixed
     */
    public function getBySlugId($slugId): Receipt
    {
        return $this->createQueryBuilder('r')
            ->where('r.slugId = :slugId')
            ->setParameter('slugId', $slugId)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * Return the rows count.
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     *
     * @return int
     */
    public function getRowCount(): int
    {
        return intval(
            $this
                ->createQueryBuilder('r')
                ->select('COUNT(r)')
                ->getQuery()
                ->getSingleScalarResult()
        );
    }

    /**
     * Get the last created receipt.
     *
     * @return mixed
     */
    public function getLastCreated()
    {
        return $this->findOneBy(
            [],
            ['createdAt' => 'desc']
        );
    }
}
